# Generated by Django 6.0.1 on 2026-01-24 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserTrustLevels',
            new_name='UserTrustLevel',
        ),
        migrations.AlterModelOptions(
            name='otpverification',
            options={'verbose_name': 'OTP'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User'},
        ),
        migrations.AlterModelOptions(
            name='useraddress',
            options={'verbose_name': 'Address', 'verbose_name_plural': 'Addresses'},
        ),
        migrations.AlterModelOptions(
            name='userdevice',
            options={'verbose_name': 'Device'},
        ),
        migrations.AlterModelOptions(
            name='usertrustlevel',
            options={'verbose_name': 'Trust Level'},
        ),
        migrations.AlterModelTable(
            name='otpverification',
            table='OTP',
        ),
        migrations.AlterModelTable(
            name='user',
            table='USER',
        ),
        migrations.AlterModelTable(
            name='useraddress',
            table='ADDRESS',
        ),
        migrations.AlterModelTable(
            name='userdevice',
            table='USER_DEVICE',
        ),
        migrations.AlterModelTable(
            name='usertrustlevel',
            table='TRUST_LEVEL',
        ),
    ]
