# Generated by Django 6.0.1 on 2026-01-24 04:52

from django.db import migrations
from pgvector.django import VectorExtension


class Migration(migrations.Migration):
    dependencies = []

    operations = [VectorExtension()]
