# Generated by Django 6.0.1 on 2026-01-24 05:45

import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client_Profile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('client_type', models.CharField(choices=[('home_owners', 'Home Owners'), ('construction_firm', 'Construction Firm')], default='home_owners', max_length=20)),
                ('company_name', models.CharField(blank=True, max_length=150, null=True)),
                ('notes', models.TextField()),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Client Profile',
                'db_table': 'CLIENT_PROFILE',
            },
        ),
        migrations.CreateModel(
            name='Skill_Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(dimensions=1536)),
            ],
            options={
                'verbose_name': 'Skill Categories',
                'db_table': 'SKILL_CATEGORY',
                'indexes': [pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='skill_category_index', opclasses=['vector_cosine_ops'])],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('is_regulated', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.skill_category')),
            ],
            options={
                'verbose_name': 'Skill',
                'db_table': 'SKILL',
            },
        ),
        migrations.CreateModel(
            name='Worker_Profile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bio', models.TextField()),
                ('bio_embedding', pgvector.django.vector.VectorField(dimensions=1536)),
                ('skill_embedding', pgvector.django.vector.VectorField(dimensions=1536)),
                ('is_available', models.BooleanField(default=True)),
                ('availability_radius_km', models.IntegerField(default=2)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Worker Profile',
                'db_table': 'WORKER_PROFILE',
            },
        ),
        migrations.CreateModel(
            name='Emergency_Contact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('phone_number', models.CharField(max_length=13)),
                ('relationship', models.CharField(blank=True, choices=[('mother', 'Mother'), ('father', 'Father'), ('sister', 'Sister'), ('brother', 'Brother'), ('relatives', 'Relatives'), ('others', 'Others')], max_length=10)),
                ('worker_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.worker_profile')),
            ],
            options={
                'verbose_name': 'Emergency Contact',
                'db_table': 'EMERGENCY_CONTACT',
            },
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='requested', max_length=10)),
                ('scheduled_at', models.DateTimeField(auto_now_add=True)),
                ('consultation_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.client_profile')),
                ('worker_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.worker_profile')),
            ],
            options={
                'verbose_name': 'Consultation',
                'db_table': 'CONSULTATION',
            },
        ),
        migrations.CreateModel(
            name='Worker_Skill',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('proof_doc_url', models.URLField()),
                ('is_verified', models.BooleanField(default=False)),
                ('skill', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='profiles.skill')),
                ('worker_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.worker_profile')),
            ],
            options={
                'verbose_name': 'Worker Skill',
                'db_table': 'WORKER_SKILL',
            },
        ),
        migrations.CreateModel(
            name='Worker_Verification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('national_id', 'National ID'), ('drivers_license', "Driver's License"), ('nbi', 'NBI')], default='drivers_license', max_length=20)),
                ('document_url', models.URLField()),
                ('status', models.CharField(choices=[('reviewing', 'Reviewing'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='reviewing', max_length=20)),
                ('reviewed_at', models.DateTimeField(auto_now=True)),
                ('worker_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='profiles.worker_profile')),
            ],
            options={
                'verbose_name': 'Worker Verification',
                'db_table': 'WORKER_VERIFICATION',
            },
        ),
        migrations.AddIndex(
            model_name='worker_profile',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['skill_index'], m=16, name='worker_skill_index', opclasses=['vector_cosine_ops']),
        ),
        migrations.AlterUniqueTogether(
            name='worker_skill',
            unique_together={('worker_id', 'skill')},
        ),
    ]
